### ISSUE TITLE
生肖不對

### ISSUE THREAD

**Issue by kingofeyesblue** [m11v/chinese_lunar_calendar#132]
這是在您計畫首頁底下的輸出資訊的節錄，這生肖就不對了，2024不是龍年嗎？你的輸出是兔年

中国标准时间：2024-02-07 14:30:00.000Z
本地时间：2024-02-06 22:30:00.000
使用本地时间计算
春节: 2024年2月10日
生肖: Zodiac(3, Located(兔, 兔))

**Comment by IreneXY** [comment]
生肖的计算不是根据阳历年（公历）计算的，因此说“2024年是龙年”是不准确的。
生肖的计算存在着以大年初一为始和以立春为始两种计算方法，是民俗学上的争议。可搜索“生肖计算争议”或类似关键字获得更多信息。

本程序提供了`startZodiacFromLiChun`参数，可根据需要设置以大年初一计算生肖或以立春计算初一：
```
factory LunarCalendar.from({
    required DateTime utcDateTime,
    startZodiacFromLiChun = false, // true: 生肖从立春开始; false: 生肖从农历初一开始
  }) 
```
示例程序是以大年初一计算生肖的。本地时间2024年2月6日早于春节2月10日，因此2024年2月6日仍旧是兔年。

**Comment by eyesblue** [comment]
感謝！明白了
