### ISSUE TITLE
正確性驗證問題

### ISSUE THREAD

**Issue by kingofeyesblue** [m11v/chinese_lunar_calendar#133]
您好
我這兩天在驗證轉換的正確性，我拿 https://github.com/m11v/chinese_lunar_calendar 與 https://github.com/m11v/chinese_lunar_calendar 做輸出比對，我的驗證方式比較粗略，我讓兩個API輸出從1901-2100的陽曆每個月的一號，然後轉換成農曆輸出，輸出資料大致如下：

1902/1/1 辛丑(牛)年十一月廿二日,
1902/2/1 辛丑(牛)年十二月廿三日, 
1902/3/1 壬寅(虎)年正月廿二日, 
1902/4/1 壬寅(虎)年二月廿三日, 
1902/5/1 壬寅(虎)年三月廿四日, 
1902/6/1 壬寅(虎)年四月廿五日, 
...
2099/10/1 己未(羊)年八月十七日, 
2099/11/1 己未(羊)年九月十九日, 
2099/12/1 己未(羊)年十月二十日,

資料大致上都一致，只有兩筆資料有問題，分別為

chinese_lunar_calendar                         JavaChineseCalendar
2057/10/1 丁丑(牛)年九月初四日            2057/10/1 丁丑(牛)年九月初三日
2089/10/1 己酉(雞)年八月廿八日            2089/10/1 己酉(雞)年八月廿七日

與此同時，我參考三個萬年曆網站，兩種結果都有：

https://www.happyfate.com.tw/web-calendar.htm
https://fate.windada.com/cgi-bin/calendar
https://www.go-calendar.com/lunar-calendar/2057-10-1

================附上我測試用的程式碼=====================

import 'dart:developer';
import 'package:chinese_lunar_calendar/chinese_lunar_calendar.dart';
 
void main() {
List<String> chMonth =['正月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'];
  String line="";
  //今天
  for(int y=1902;y<2100;y++){
    for(int m=1;m<13;m++){
      final lunarCalendar = LunarCalendar.from(
      utcDateTime: DateTime(y, m, 1).toUtc(),
      );
      String leapStr=(lunarCalendar.lunarDate.lunarMonth.isLeapMonth?"閏":"");
      line +="$y/$m/1 ${lunarCalendar.year8Char}(${lunarCalendar.zodiac.name.getValue()})年$leapStr${chMonth[lunarCalendar.lunarDate.lunarMonth.number-1]}${lunarCalendar.lunarDate.lunarDayCN}日, ";
    }
    line += "\n";
  }
  
  log("$line");
}

========================================================

還請確認是否換算有問題，謝謝！

**Comment by IreneXY** [comment]
日期的计算和节气数据相关。本程序及参考项目https://github.com/OPN48/cnlunar/tree/master 均使用的是香港天文台提供的节气数据，因此计算数据与香港天文台提供的数据一致。香港天文台的数据请见https://www.weather.gov.hk/tc/gts/time/conversion.htm。
