### ISSUE TITLE
是否支持 2022 年之前？

### ISSUE THREAD

**Issue by iamshaunwu** [m11v/chinese_lunar_calendar#51]
是否能支持 2022 年 12 月 31 日之前，至少到 1900 年？当凡输入2022 年 12 月 31 日之前的日期都会出现一下的错误：
`The following IndexError was thrown while handling a gesture:
RangeError (index): Index out of range: no indices are valid: 22`

**Comment by IreneXY** [comment]
完成。
#112 支持了1901年到2100年的数据。已经合并到main中。将在1.0版本发布。
